services:
  - type: web
    name: forest-fire-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free
